#!/usr/bin/env python3
"""Mirror BSB Old Testament output files into the MSB output tree.

For every BSB OT file under bereanbible/, write a copy to the matching
relative path under majoritybible/, with two normalisations:

  - Filename:  the "BSB" token is rewritten to "MSB"
               (e.g. 01GENBSB_int.usfm -> 01GENMSB_int.usfm).
  - Content:   the single "Autogenerated BSB" string on the \\id header
               line is rewritten to "Autogenerated MSB", so the resulting
               file identifies itself as part of the MSB collection.
               No other content is modified.

Subdirectories under bereanbible/ that contain no book files
(workspace/, temp/) are skipped.
"""

import re
import sys
from pathlib import Path

OT_CODES = {
    "GEN", "EXO", "LEV", "NUM", "DEU", "JOS", "JDG", "RUT",
    "1SA", "2SA", "1KI", "2KI", "1CH", "2CH", "EZR", "NEH",
    "EST", "JOB", "PSA", "PRO", "ECC", "SNG", "ISA", "JER",
    "LAM", "EZK", "DAN", "HOS", "JOL", "AMO", "OBA", "JON",
    "MIC", "NAM", "HAB", "ZEP", "HAG", "ZEC", "MAL",
}

SOURCE_ROOT = Path("bereanbible")
TARGET_ROOT = Path("majoritybible")
SKIP_DIRS = {"workspace", "temp"}

VARIANT_RE = re.compile(r"^\d{2}([A-Z0-9]{3})BSB")


def book_code(stem: str) -> str | None:
    if stem in OT_CODES:
        return stem
    m = VARIANT_RE.match(stem)
    if m and m.group(1) in OT_CODES:
        return m.group(1)
    return None


def main() -> int:
    if not SOURCE_ROOT.is_dir():
        print(f"error: {SOURCE_ROOT}/ not found", file=sys.stderr)
        return 1

    count = 0
    for src in SOURCE_ROOT.rglob("*"):
        if not src.is_file():
            continue
        if src.relative_to(SOURCE_ROOT).parts[0] in SKIP_DIRS:
            continue
        if book_code(src.stem) is None:
            continue

        rel = src.relative_to(SOURCE_ROOT)
        dst = TARGET_ROOT / rel.parent / src.name.replace("BSB", "MSB")
        dst.parent.mkdir(parents=True, exist_ok=True)

        content = src.read_text(encoding="utf-8")
        content = content.replace("Autogenerated BSB", "Autogenerated MSB", 1)
        dst.write_text(content, encoding="utf-8")
        count += 1

    print(f"Mirrored {count} BSB OT files into {TARGET_ROOT}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
